SPEC_REGISTRY = {
    "MP_ITEM_MATCH": {
        "name": "Offer setup by match",
        "feed_type": "MP_ITEM_MATCH",
        "recommended": "MP_ITEM_MATCHv4.2",
        "previous": None,
        "not_recommended": None,
        "diff_report": None,
        "category": "Item Setup",
    },
    "MP_ITEM": {
        "name": "Create new items for MP (SFF fulfilled)",
        "feed_type": "MP_ITEM",
        "recommended": "5.0.20260501-19_21_29-api",
        "previous": "5.0.20260330-14_47_14-api",
        "not_recommended": "5.0.20260304-22_45_32-api",
        "diff_report": "MP Item spec version report",
        "category": "Item Setup",
    },
    "MP_MAINTENANCE": {
        "name": "Maintain existing Items for MP (SFF) and WFS",
        "feed_type": "MP_MAINTENANCE",
        "recommended": "5.0.20260501-19_21_29-api",
        "previous": "5.0.20260330-14_47_14-api",
        "not_recommended": "5.0.20260304-22_45_32-api",
        "diff_report": "MP maintenance spec version report",
        "category": "Item Maintenance",
    },
    "MP_WFS_ITEM": {
        "name": "Create new items for WFS",
        "feed_type": "MP_WFS_ITEM",
        "recommended": "5.0.20260501-19_21_29-api",
        "previous": "5.0.20260330-14_47_14-api",
        "not_recommended": "5.0.20260304-22_45_32-api",
        "diff_report": "WFS item spec version report",
        "category": "WFS",
    },
    "OMNI_WFS": {
        "name": "Convert existing item to WFS",
        "feed_type": "OMNI_WFS",
        "recommended": "5.0.20260501-19_21_29-api",
        "previous": "5.0.20260330-14_47_14-api",
        "not_recommended": "5.0.20260304-22_45_32-api",
        "diff_report": "WFS convert spec version report",
        "category": "WFS",
    },
    "DELETE_ITEM": {
        "name": "Bulk item delete",
        "feed_type": "DELETE_ITEM",
        "recommended": "5.0.20260330-14_47_14-api",
        "previous": None,
        "not_recommended": None,
        "diff_report": None,
        "category": "Item Delete",
    },
    "CATEGORY_MAPPING": {
        "name": "Category mapping updates",
        "feed_type": None,
        "recommended": None,
        "previous": None,
        "not_recommended": None,
        "diff_report": "Migration documentation",
        "category": "Migration",
    },
    "DIFF_4X_TO_5X": {
        "name": "4.X to 5.X Diff Report",
        "feed_type": "All",
        "recommended": None,
        "previous": None,
        "not_recommended": None,
        "diff_report": "Migration documentation",
        "category": "Migration",
    },
    "FITMENT_ACES": {
        "name": "Fitment ACES XML/XLSX file",
        "feed_type": "FITMENT_ACES",
        "recommended": "ACES-XLSX-sample",
        "previous": None,
        "not_recommended": None,
        "diff_report": None,
        "category": "Fitment",
    },
    "FITMENT_PIES": {
        "name": "Fitment PIES sample file",
        "feed_type": "FITMENT_PIES",
        "recommended": "PIES-sample-file",
        "previous": None,
        "not_recommended": None,
        "diff_report": None,
        "category": "Fitment",
    },
}
